import{a as y,S as p,i as c}from"./assets/vendor-DxEWe7lX.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&r(l)}).observe(document,{childList:!0,subtree:!0});function a(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(e){if(e.ep)return;e.ep=!0;const o=a(e);fetch(e.href,o)}})();const g="46793752-15e3775c3640735c851618a54",h="https://pixabay.com/api/",b=15;async function w(t,s=1){const a=`${h}?key=${g}&q=${encodeURIComponent(t)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${b}&page=${s}`;return(await y.get(a)).data}let i=null;function L(t){const s=document.querySelector(".gallery"),a=t.map(r=>`
      <a href="${r.largeImageURL}" class="gallery-item">
        <img src="${r.webformatURL}" alt="${r.tags}" title="${r.tags}" class="gallery-image"/>
        <div class="info">
          <p class="article-strick"><b class="main-word">Likes:</b> ${r.likes}</p>
          <p class="article-strick"><b class="main-word">Views:</b> ${r.views}</p>
          <p class="article-strick"><b class="main-word">Comments:</b> ${r.comments}</p>
          <p class="article-strick"><b class="main-word">Downloads:</b> ${r.downloads}</p>
        </div>
      </a>`).join("");s.insertAdjacentHTML("beforeend",a),i?i.refresh():i=new p(".gallery a")}function S(){document.querySelector(".gallery").innerHTML=""}function q(){document.querySelector(".load-more").style.display="block"}function f(){document.querySelector(".load-more").style.display="none"}function $(){iziToast.info({title:"Info",message:"We're sorry, but you've reached the end of search results."})}let u="",n=1,d=0;function v(){document.querySelector(".loader").style.display="block"}function E(){document.querySelector(".loader").style.display="none"}document.querySelector(".search-form").addEventListener("submit",async t=>{if(t.preventDefault(),u=t.target.elements.searchQuery.value.trim(),n=1,!u){c.warning({title:"Warning",message:"Please enter a search query."});return}S(),f(),await m()});document.querySelector(".load-more").addEventListener("click",m);async function m(){v();try{const t=await w(u,n);d=t.totalHits,t.hits.length===0?c.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(L(t.hits),n*15<d?q():(f(),$()),P(),n+=1)}catch{c.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{E()}}function P(){const{height:t}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:t*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
